variables:
  CRAN_REPO: https://cloud.r-project.org
  BUILD_DIR: build

build-job:
  stage: build
  script:
    # The package is build and tested using a the local packages of gitlab-runner.
    # All packages are up-to-date before the package is build and the check is run.
    - echo "R_LIBS_USER=~/R/cpb_r_packages/%v" > .Renviron
    - echo "R_LIBS_SITE=''" >> .Renviron
    - Rscript -e "lib_dir <- Sys.getenv('R_LIBS_USER'); if(!dir.exists(lib_dir)) dir.create(lib_dir, recursive = TRUE)"
    - Rscript -e "print(.libPaths())"
    - Rscript -e "if (!require(devtools)) install.packages('devtools', repos = '$CRAN_REPO')"
    - Rscript -e "devtools::install_deps('pkg', dependencies = TRUE, repos = '$CRAN_REPO')"
    - R CMD build pkg 
    - mkdir $BUILD_DIR
    - mv *.tar.gz $BUILD_DIR
  artifacts:
    paths:
      - build

test-job1:
  stage: test
  script:
    - echo "R_LIBS_USER=~/R/cpb_r_packages/%v" > .Renviron
    - echo "R_LIBS_SITE=''" >> .Renviron
    - Rscript -e "print(.libPaths())"
    - ls -l $BUILD_DIR
    - R CMD check $BUILD_DIR/*.tar.gz
