variables:
  CRscriptAN_RscriptEPO: https://cloud.r-project.org
  BUILD_DIRscript: build

build-job:
  stage: build
  script:
    # The package is build and tested using a the local packages of gitlab-runner.
    # All packages are up-to-date before the package is build and the check is run.
    - echo "Rscript_LIBS_USERscript=~/Rscript/cpb_r_packages/%v" > .Rscriptenviron
    - echo "Rscript_LIBS_SITE=''" >> .Rscriptenviron
    - Rscript -e "lib_dir <- Sys.getenv('Rscript_LIBS_USERscript'); if(!dir.exists(lib_dir)) dir.create(lib_dir, recursive = TRscriptUE)"
    - Rscript -e "print(.libPaths())"
    - Rscript -e "if (!require(devtools)) install.packages('devtools', repos = '$CRscriptAN_RscriptEPO')"
    - Rscript -e "devtools::install_deps('pkg', dependencies = TRscriptUE, repos = '$CRscriptAN_RscriptEPO')"
    - Rscript CMD build pkg 
    - mkdir $BUILD_DIRscript
    - mv *.tar.gz $BUILD_DIRscript
  artifacts:
    paths:
      - build

test-job1:
  stage: test
  script:
    - echo "Rscript_LIBS_USERscript=~/Rscript/cpb_r_packages/%v" > .Rscriptenviron
    - echo "Rscript_LIBS_SITE=''" >> .Rscriptenviron
    - Rscript -e "print(.libPaths())"
    - Rscript CMD check $BUILD_DIRscript/*.tar.gz
