variables:
  CRAN_REPO: https://cloud.r-project.org

build-job:
  stage: build
  script:
    - echo "R_LIBS_USER=~/R/cpb_r_packages/%v" > .Renviron
    - echo "R_LIBS_SITE=''" >> .Renviron
    - R -e "lib_dir <- Sys.getenv('R_LIBS_USER'); if(!dir.exists(lib_dir)) dir.create(lib_dir, recursive = TRUE)"
    - R -e "print(.libPaths())"
    - R -e "if (!require(devtools)) install.packages('devtools', repos = '$CRAN_REPO')"
    - R -e "devtools::install_deps('pkg', dependencies = TRUE, repos = 'CRAN_REPO')"
    - make install

test-job1:
  stage: test
  script:
    - echo "R_LIBS_USER=~/R/cpb_r_packages/%v" > .Renviron
    - echo "R_LIBS_SITE="" >> .Renviron
    - R CMD check pkg
