variables:
  BUILD_DIR: build

before_script:
    - echo "R_LIBS_USER=~/R/cpb_r_packages/%v" > .Renviron
    - echo "R_LIBS_SITE=''" >> .Renviron

build-job:
  stage: build
  script:
    # The package is build and tested using a the local packages of gitlab-runner.
    - Rscript ci_scripts/prepare_local_lib.R
    - R CMD build pkg 
    - mkdir $BUILD_DIR
    - mv *.tar.gz $BUILD_DIR
  artifacts:
    paths:
      - build

test-job1:
  stage: test
  script:
    - Rscript -e "print(.libPaths())"
    - R CMD check $BUILD_DIR/*.tar.gz
    - Rscript ci_scripts/lint_pkg.R
