build-job:
  stage: build
  script:
    - whoami
    - pwd
    - echo $HOME
    - echo "R_LIBS_USER=~/R/cpb_r_packages/%v" > .Renviron
    - R -e "print(.libPaths())"
    - make install

test-job1:
  stage: test
  script:
    - echo "R_LIBS_USER=~/R/cpb_r_packages/%v" > .Renviron
    - echo "This job tests something"
    - R CMD check pkg


deploy-prod:
  stage: deploy
  script:
    - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."
  environment: production
