# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

agg_gr <- function(ts_old, freq_new, method) {
    .Call(`_regts_agg_gr`, ts_old, freq_new, method)
}

disagg_spline <- function(ts_old, freq_new, constraint, method) {
    .Call(`_regts_disagg_spline`, ts_old, freq_new, constraint, method)
}

moving_average <- function(x, w, from, to, keep_range) {
    .Call(`_regts_moving_average`, x, w, from, to, keep_range)
}

parse_period <- function(period_text, frequency) {
    .Call(`_regts_parse_period`, period_text, frequency)
}

parse_period_range <- function(period_text, frequency) {
    .Call(`_regts_parse_period_range`, period_text, frequency)
}

is_period_text <- function(strings, frequency) {
    .Call(`_regts_is_period_text`, strings, frequency)
}

#' Return the \link{period_range} of a timeseries.
#'
#' @param x a timeseries (\link{ts} or \link{regts})
#' @return a \code{period_range}
#' @export
#' @seealso \code{\link{get_periods}}
get_period_range <- function(x) {
    .Call(`_regts_get_period_range`, x)
}

regts_to_list <- function(ts) {
    .Call(`_regts_regts_to_list`, ts)
}

rel2index_cpp <- function(grts, first_base_row) {
    .Call(`_regts_rel2index_cpp`, grts, first_base_row)
}

