# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

agg_gr <- function(ts_old, freq_new, method) {
    .Call('regts_agg_gr', PACKAGE = 'regts', ts_old, freq_new, method)
}

parse_rperiod <- function(period_text, frequency) {
    .Call('regts_parse_rperiod', PACKAGE = 'regts', period_text, frequency)
}

parse_rperiod_range <- function(period_text, frequency) {
    .Call('regts_parse_rperiod_range', PACKAGE = 'regts', period_text, frequency)
}

is_period_text_ <- function(strings, given_freq) {
    .Call('regts_is_period_text_', PACKAGE = 'regts', strings, given_freq)
}

#' Returns the \link{period_range} of a timeseries.
#'
#' @param x a timeseries (\link{ts} or \link{regts})
#' @return a \code{period_range}
#' @export
get_period_range <- function(x) {
    .Call('regts_get_period_range', PACKAGE = 'regts', x)
}

