// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// agg_gr
NumericMatrix agg_gr(NumericMatrix x, int rep, int first_old, int first_new);
RcppExport SEXP regts_agg_gr(SEXP xSEXP, SEXP repSEXP, SEXP first_oldSEXP, SEXP first_newSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type rep(repSEXP);
    Rcpp::traits::input_parameter< int >::type first_old(first_oldSEXP);
    Rcpp::traits::input_parameter< int >::type first_new(first_newSEXP);
    __result = Rcpp::wrap(agg_gr(x, rep, first_old, first_new));
    return __result;
END_RCPP
}
