context("start_period, end_period")

test_that("start_period and end_period for regperiod_range", {
    r <- regperiod_range("2010Q4", "2011Q3")
    expect_identical(start_period(r), regperiod("2010Q4"))
    expect_identical(end_period(r), regperiod("2011Q3"))
    r <- regperiod_range("2010", NULL)
    expect_identical(start_period(r), regperiod("2010"))
    expect_identical(end_period(r), NULL)
    r <- regperiod_range(NULL, "2010m3")
    expect_identical(start_period(r), NULL)
    expect_identical(end_period(r), regperiod("2010M3"))
})

test_that("start_period and end_period for regts", {
    range <- regperiod_range("2010Q4", "2011Q3")
	regts1 <- regts(1:4, period = range)
    expect_identical(start_period(regts1), regperiod("2010Q4"))
    expect_identical(end_period(regts1), regperiod("2011Q3"))
    range <- regperiod_range("2010", "2010")
	regts2 <- regts(1, period = range)
    expect_identical(start_period(regts2), end_period(regts2))
	regts3 <- regts(1:11, start = "2010")
	expect_identical(start_period(regts3), regperiod("2010"))
	expect_identical(end_period(regts3), start_period(regts3) + 10)
	regts4 <- regts(1:11, period = "2010/")
	expect_identical(start_period(regts4), regperiod("2010"))
	expect_identical(end_period(regts4), start_period(regts4) + 10)
})
