# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

agg_gr <- function(ts, freq_new) {
    .Call('regts_agg_gr', PACKAGE = 'regts', ts, freq_new)
}

