# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

agg_gr <- function(ts_old, freq_new, method) {
    .Call('regts_agg_gr', PACKAGE = 'regts', ts_old, freq_new, method)
}

parse_regperiod <- function(period_text, frequency) {
    .Call('regts_parse_regperiod', PACKAGE = 'regts', period_text, frequency)
}

parse_regperiod_range <- function(period_text, frequency) {
    .Call('regts_parse_regperiod_range', PACKAGE = 'regts', period_text, frequency)
}

#' Returns the \link{regperiod_range} of a timeseries.
#'
#' @param x a timeseries (\link{ts} or \link{regts})
#' @return a \code{regperiod_range}
#' @export
get_regperiod_range <- function(ts) {
    .Call('regts_get_regperiod_range', PACKAGE = 'regts', ts)
}

#' @export
window_numregts <- function(ts_old, range) {
    .Call('regts_window_numregts', PACKAGE = 'regts', ts_old, range)
}

